"""Initial schema sync

Revision ID: 7cc953864710
Revises: 
Create Date: 2026-05-25 17:38:06.442213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc953864710'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('qr_scan_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location_data', sa.String(length=255), nullable=True))
        
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=45),
               existing_nullable=True)
        
        # REMOVE the drop_constraint line completely
        # Just create the new foreign key
        batch_op.create_foreign_key('fk_qrscanlog_vault_id', 'vault_profiles', ['vault_id'], ['id'])
        
        batch_op.drop_column('location')
        batch_op.drop_column('scanned_at')
        batch_op.drop_column('emergency_triggered')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_scan_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('scanned_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('emergency_triggered', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('fk_qrscanlog_vault_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vault_profiles', ['vault_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('vault_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('location_data')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
